# Generated by Django 4.0.2 on 2022-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_EnteteBL_BL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BL_Num', models.IntegerField(unique=True)),
                ('BL_Cial', models.CharField(max_length=30)),
                ('BL_Date', models.DateTimeField()),
                ('BL_NomClient', models.CharField(max_length=50)),
                ('BL_RefClient', models.CharField(max_length=70)),
                ('BL_Chantier', models.CharField(max_length=15)),
                ('BL_Adr1Liv', models.CharField(max_length=30)),
                ('BL_Adr2Liv', models.CharField(max_length=30)),
                ('BL_Adr3Liv', models.CharField(max_length=30)),
                ('BL_CpLiv', models.CharField(max_length=5)),
                ('BL_VilleLiv', models.CharField(max_length=30)),
                ('BL_Observ', models.TextField(max_length=2000)),
                ('BL_Comment', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='T_LigneBL_BLI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLI_Num', models.IntegerField(unique=True)),
                ('BLI_BL_Num', models.IntegerField()),
                ('BLI_Select', models.BooleanField(default=False)),
                ('BLI_CodeProduit', models.IntegerField()),
                ('BLI_Libel', models.CharField(max_length=60)),
                ('BLI_Qte', models.IntegerField()),
                ('BLI_Unite', models.CharField(choices=[('ML', 'Mètre linéaire'), ('UN', 'Unité')], default='ML', max_length=3)),
            ],
        ),
    ]
