# Generated by Django 4.0.2 on 2022-03-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BL_Entete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BL_Num', models.IntegerField(unique=True)),
                ('BL_Cial', models.CharField(blank=True, max_length=30)),
                ('BL_Date', models.DateTimeField(blank=True, null=True)),
                ('BL_NomClient', models.CharField(blank=True, max_length=50, null=True)),
                ('BL_RefClient', models.CharField(max_length=70)),
                ('BL_Chantier', models.CharField(blank=True, max_length=15)),
                ('BL_Adr1Liv', models.CharField(blank=True, max_length=30)),
                ('BL_Adr2Liv', models.CharField(blank=True, max_length=30)),
                ('BL_Adr3Liv', models.CharField(blank=True, max_length=30)),
                ('BL_CpLiv', models.CharField(blank=True, max_length=5)),
                ('BL_VilleLiv', models.CharField(blank=True, max_length=30)),
                ('BL_Observ', models.TextField(blank=True, max_length=2000)),
                ('BL_Comment', models.TextField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='BL_Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLI_Num', models.IntegerField(blank=True, null=True, unique=True)),
                ('BLI_BL_Num', models.IntegerField()),
                ('BLI_Select', models.BooleanField(default=False)),
                ('BLI_CodeProduit', models.IntegerField(blank=True)),
                ('BLI_Libel', models.CharField(blank=True, max_length=60)),
                ('BLI_Qte', models.IntegerField(blank=True)),
                ('BLI_Unite', models.CharField(blank=True, choices=[('ML', 'Mètre linéaire'), ('UN', 'Unité')], max_length=3)),
                ('BL_entete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='wprod.bl_entete')),
            ],
        ),
        migrations.DeleteModel(
            name='T_EnteteBL_BL',
        ),
        migrations.DeleteModel(
            name='T_LigneBL_BLI',
        ),
    ]
