# Generated by Django 4.0.2 on 2022-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0002_bl_entete_bl_ligne_delete_t_entetebl_bl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_ligne',
            name='BLI_CodeProduit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
