# Generated by Django 4.0.2 on 2022-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0003_alter_bl_ligne_bli_codeproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_ligne',
            name='BLI_Qte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
