# Generated by Django 4.0.2 on 2022-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0004_alter_bl_ligne_bli_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Adr1Liv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Adr2Liv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Adr3Liv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Chantier',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Cial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_CpLiv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_Observ',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='BL_VilleLiv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='BLI_BL_Num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
