# Generated by Django 4.0.2 on 2022-03-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0005_alter_bl_entete_bl_adr1liv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bl_ligne',
            old_name='BL_entete',
            new_name='BL_entete_id',
        ),
    ]
