# Generated by Django 4.0.2 on 2022-03-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0008_rename_bli_bl_num_bl_ligne_bli_bl_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bl_ligne',
            old_name='bl_entete_id',
            new_name='bl_entete',
        ),
    ]
