# Generated by Django 4.0.2 on 2022-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0010_bl_ligne_bli_pu_bl_ligne_bli_pu_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl_ligne',
            name='bli_comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bl_ligne',
            name='bli_observ',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
