# Generated by Django 4.0.2 on 2022-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0012_alter_bl_ligne_bli_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_libel',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_unite',
            field=models.CharField(blank=True, choices=[('ML', 'Mètre linéaire'), ('UN', 'Unité'), ('M2', 'Mètre carré'), ('KG', 'Kilogramme'), ('M3', 'Mètre cube'), ('TO', 'Tonne')], max_length=3, null=True),
        ),
    ]
