# Generated by Django 4.0.2 on 2022-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0013_alter_bl_ligne_bli_libel_alter_bl_ligne_bli_unite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
