# Generated by Django 4.0.2 on 2022-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0014_alter_bl_ligne_bli_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='bl_entete',
            name='bl_dateimport',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
