# Generated by Django 4.0.2 on 2022-03-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0015_bl_entete_bl_dateimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bl_entete',
            name='bl_num',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_bl_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_codeproduit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_num',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
