# Generated by Django 4.0.2 on 2022-03-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0016_alter_bl_entete_bl_num_alter_bl_ligne_bli_bl_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bl_entete',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bl_ligne',
            name='bli_bl_num',
        ),
        migrations.RemoveField(
            model_name='bl_ligne',
            name='id',
        ),
        migrations.AlterField(
            model_name='bl_entete',
            name='bl_num',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bl_entete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lignes', related_query_name='ligne', to='wprod.bl_entete'),
        ),
        migrations.AlterField(
            model_name='bl_ligne',
            name='bli_num',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
