# Generated by Django 4.0.2 on 2022-03-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0017_remove_bl_entete_id_remove_bl_ligne_bli_bl_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bl_ligne',
            old_name='bl_entete',
            new_name='bli_bl_num',
        ),
    ]
