# Generated by Django 4.0.2 on 2022-03-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wprod', '0019_alter_bl_entete_options_alter_bl_ligne_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bl_entete',
            options={'ordering': ('-bl_num',)},
        ),
        migrations.AlterModelOptions(
            name='bl_ligne',
            options={'ordering': ('-bli_bl_num', '-bli_num', 'bli_codeproduit')},
        ),
    ]
